### ISSUE TITLE
Branje datumov

### ISSUE THREAD

**Issue by jaanos** [zaloznikjan7/APPR-2019-20#1]
Vidim, da imaš v eni od uvoženih razpredelnic datume, ki pa so trenutno predstavljeni kot nizi. V datume jih lahko pretvoriš s funkcijo `parse_date`, npr.
```R
  tabela %>% transmute(Name, Club,
                       Appointed=parse_date(Appointed, "%d %B %Y",
                                            locale=locale("en")))
```
Funkcija `transmute` deluje podobno kot `select`, le da dovoli tudi spreminjanje stolpcev.

**Comment by zaloznikjan7** [comment]
Popravljeno, hvala :)

**Comment by jaanos** [comment]
Ko razrešiš problem, lahko issue zapreš. Spremembe sicer ne vidim, tako da bom zaenkrat pustil odprto (morda še nisi naredil commit/push).

Issue lahko zapreš tudi tako, da v sporočilo ob commitu vključiš *Close #1*, kjer je #1 številka issueja.
