### ISSUE TITLE
Funkcije iz dplyr s parametri iz vektorja

### ISSUE THREAD

**Issue by jaanos** [zaloznikjan7/APPR-2019-20#3]
Danes sva gledala, kako se izogniti opozorilu zaradi uporabe funkcij `select_` in `rename_`. Potrebno bo uporabiti različici brez podčrtaja, parametre pa lahko podaš s trojnim klicajem in funkcijo `syms`:
```R
    Sezona <- read_csv(datoteka, locale=locale(encoding="utf8")) %>%
      select(!!! syms(kaj_obravnavam)) %>%
      rename(!!! syms(nova_imena))
```
Funkcija `syms` namreč iz znakovnega vektorja naredi seznam izrazov, trojni klicaj pa pri funkcijah iz knjižnice `dplyr` poskrbi, da se vsaka spremenljivka iz takega seznama razume kot parameter funkcije.

**Comment by zaloznikjan7** [comment]
Žal se je program zopet pritožil.. 
<img width="444" alt="Screenshot 2020-03-28 at 17 10 54" src="https://user-images.githubusercontent.com/57746808/77827681-602d7600-7117-11ea-90a1-3595121f3282.png">

**Comment by jaanos** [comment]
Morda nimaš naložene zadnje različice knjižnice `dplyr`, tako da jo poskusi znova namestiti.
