### ISSUE TITLE
Zemljevidi

### ISSUE THREAD

**Issue by zaloznikjan7** [zaloznikjan7/APPR-2019-20#4]
Prosil, bi vas če lahko pogledate v vizualizacijo in mi samo spročite če lahko uporabljam ta novi način (pripravil sem samo 3 mesta za primer) ali ne, saj s tmap nisem nikjer najdel možnosti da dodam koordinate (prebral sem tudi dokumentacijo). 
lep pozdrav Jan

**Comment by jaanos** [comment]
Predlagam, da pri funkciji `uvozi.zemljevid` namesto `"gadm36_GBR_1"` podaš `"gadm36_GBR_2"` - tako dobiš zemljevid z okrožji (imena so v stolpcu `NAME_2`). Potem lahko za vsak klub pridobiš podatek, kateremu okrožju pripada (kar verjetno ne bo veliko manj specifično, kot če klube deliš po mestih), ter ustrezno barvaš ta okrožja. Po potrebi lahko uporabiš še podrobnejši zemljevid `"gadm36_GBR_3"`.
