### ISSUE TITLE
Napredna analiza

### ISSUE THREAD

**Issue by zaloznikjan7** [zaloznikjan7/APPR-2019-20#5]
Težavo imam pri napredni analizi, kjer mi pri drugi in tretji točki merge ne združi pravilno podatkov. Hvala za pomoč.

**Comment by jaanos** [comment]
Najprej, če uporabljaš `rownames` na rezultatu `inner_join`, dobiš opozorilo, zato bo bolje podatke pretvoriti v običajno razpredelnico:
```R
tocke_domaci_gosti <- inner_join(tocke_domacii, gostujoce_tocke) %>% data.frame()
rownames(tocke_domaci_gosti) <- tocke_domaci_gosti$Ekipa
razdelitev <- tocke_domaci_gosti %>% select(-Ekipa) %>% scale() %>% kmeans(5)
```
Problem se potem pojavi, ker se nekatere regije pojavijo večkrat (poleg Londona še Bolton, Birmingham, Blackpool - preveri, če je vse v redu!). Treba bo torej narediti `group_by` - ker na skupinah ni nobene smiselne operacije, vzamemo kar urejen seznam skupin v regiji. Enako naredimo tudi za klube:
```R
skupine <- data.frame(Ekipa=tocke_domaci_gosti$Ekipa, Skupina=factor(razdelitev$cluster),
                      stringsAsFactors=FALSE)
tocke_regije3 <- skupine %>% inner_join(klubi.regija) %>%
  group_by(Regija) %>% summarise(Ekipa=unique(Ekipa) %>% sort() %>% paste(collapse=", "),
                                 Skupina=unique(Skupina) %>% sort() %>% paste(collapse=", "),
                                 Stevilo=n())
```
Tako se vsaka regija pojavi samo enkrat, zraven pa je še podatek o ekipah, skupinah in številu pojavitev regije.

Sedaj lahko izrišeš zemljevid:
```R
zem.tocke3 <- merge(EngWal, tocke_regije3, by.x="NAME_2", by.y="Regija")
zemljevid_skupin <- tm_shape(zem.tocke3) + tm_polygons("Skupina")
```
Glede na to, da je pobarvan le manjši del zemljevida, pri čemer obstaja nekaj gruč klubov, ki so geografsko blizu skupaj, bi morda bilo smiselno bližje prikazati te zanimive dele (poleg seveda samega Londona). Zraven lahko izpišeš še imena klubov, npr.
```R
tm_shape(zem.tocke3, xlim=c(-3.2, -1.7), ylim=c(53.3, 53.9)) + tm_polygons("Skupina") +
  tm_legend(show=FALSE) + tm_text("Ekipa", size=0.7)
```

**Comment by zaloznikjan7** [comment]
Super, hvala za pomoč.
