### ISSUE TITLE
Končal sem projekt

### ISSUE THREAD

**Issue by zaloznikjan7** [zaloznikjan7/APPR-2019-20#6]

**Comment by jaanos** [comment]
Poročilo se prevede, tako da bom dodal povezavo do tvojega projekta na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Čeprav se poročilo prevede, pa se vsi grafi pri meni ne prikažejo. Težava je v uporabi šumnikov in presledkov v imenih blokov kode (tj., ime za `r` in pred vejico). Tako namesto npr. `Najuspešnejše ekipe` raje uporabi `Najuspesnejse_ekipe`.

Druga pripomba je bolj estetske narave - barve na zemljevidu Londona se ne ujemajo z barvami na predhodnih zemljevidih. Problem je seveda v oznaki za London - ker je to sedaj edina regija z več klubi, se lahko ta posebej označi z oznako, ki bo prišla na koncu legende, npr.
```R
tocke_regije3 <- skupine %>% inner_join(klubi.regija) %>%
  group_by(Regija) %>% summarise(Ekipa=unique(Ekipa) %>% sort() %>% paste(collapse=", "),
                                 Skupina=ifelse(n() == 1, paste(Skupina), "London"))
```
Ker Londona tudi na drugih podrobnejših zemljevidih ni, ga lahko odstraniš iz podatkov, da ga tudi v legendi ne bo, npr.
```R
tocke_brezLondona <- tocke_regije3 %>% filter(Skupina != "London")
zem.tocke3_brezLondona <- merge(EngWal, tocke_brezLondona, by.x="NAME_2", by.y="Regija")
```
Potem lahko pri podrobnejših zemljevidih uporabih `zem.tocke3_brezLondona`.

**Comment by jaanos** [comment]
Še to: glede na to, da nimaš aplikacije Shiny, lahko iz glave poročila odstraniš vrstico `runtime: shiny`.

**Comment by zaloznikjan7** [comment]
Super, sem popravil vse napake. Hvala za pomoč.

**Comment by jaanos** [comment]
V redu, sem posodobil. Še vedno imaš sicer presledke v imenih blokov kode, zaradi česar se nekateri grafi ne prikažejo pri poganjanju v Binderju.

**Comment by zaloznikjan7** [comment]
Pa res, sem sedaj popravil tudi to.

**Comment by jaanos** [comment]
V redu, sem posodobil.
